spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: volkovdenis8998@gmail.com
    password: "srzriwyzpjezjpsi"
    test-connection: true # проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender: # отправить письма (почта и имя)
      email: no-reply@example.com
      text: no-reply